name: CI
on: [push]
jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@master

      - name: Setup Node.js
        uses: 'actions/setup-node@v1'
        with:
          node-version: '14.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Setup npm
        run: npm i -g npm@7 --registry=https://registry.npmjs.org && npm --version

      - name: Install dependencies
        run: npm install --workspaces

      - name: Test
        run: npm test --workspaces

      - name: Create .npmrc
        run: |
          cat << EOF > "$HOME/.npmrc"
            //registry.npmjs.org/:_authToken=$NPM_TOKEN
          EOF
        env:
          NPM_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

      - name: Release snapshot
        run: |
          npx changeset version --snapshot
          npx changeset publish --tag canary
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
