name: CI
on: [push]
jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@master

      - name: Set up Node.js 10.x
        uses: actions/setup-node@master
        with:
          version: 10

      - name: Install dependencies
        run: yarn

      - name: Test
        run: yarn workspace @primer/gatsby-theme-doctocat test

      - name: Prerelease
        run: |
          yarn changeset pre enter canary
          yarn changeset version
          yarn changeset publish
