name: CI
on: [push]
jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@master

      - name: Set up Node.js 10.x
        uses: actions/setup-node@master
        with:
          node-version: 10

      - name: Install dependencies
        run: yarn

      - name: Test
        run: yarn workspace @primer/gatsby-theme-doctocat test

      - name: Create .npmrc
        run: |
          cat << EOF > "$HOME/.npmrc"
            //registry.npmjs.org/:_authToken=$NPM_TOKEN
          EOF
        env:
          NPM_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

      - name: Snapshot release
        run: |
          yarn changeset version --snapshot
          yarn changeset publish --tag canary
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
