name: Release
on:
  push:
    branches:
      - master
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@master
        with:
          # This makes Actions fetch all Git history so that Changesets can generate changelogs with the correct commits
          fetch-depth: 0

      - name: Setup Node.js
        uses: 'actions/setup-node@v1'
        with:
          node-version: '14.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Setup npm
        run: npm i -g npm@7 --registry=https://registry.npmjs.org && npm --version

      - name: Install dependencies
        run: npm install --workspaces

      - name: Create release pull request or publish to npm
        id: changesets
        uses: changesets/action@master
        with:
          publish: npm run release --workspaces
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
